### Dúvidas:

- Total de colunas: 11
        - Sim, só muda se houver solicitação de inclusão de mais campos.

- Nome da aba é sempre "dados"?
        - Sim, já vem diretamento do sistema de vendas.

- Qual a origem dos relatórios?
        - Resp.: São extraídos do sistema de venda

- Data é a data de realização da venda? 
        - Resp.: Sim, já vem diretamento do sistema de vendas.

- Quem são os compradores?
    - Nome do arquivo tem algo a ver com isso?
        - Resp.: Nome do arquivo é cofiguraddo da seguinte forma:
                    'nome do segmento - país onde foi realizada a venda'

- A estrutura dos arquivos permanecerá a mesma, pelo menos por enquanto.
 
 Passo a Passo
 1. Criar uma planilha em branco: Consolidado (planilha que terá todas as informações)
 2. Replicar as colunas que existem  nos relatórios (11 colunas)
 3. Inserir mais duas colunas: Segmento e País.
 4. Percorrer todos os arquivos, copiar os dados, colar na planilha consolidado e preencher as informações de segmento e país.

In [5]:
import pandas as pd
import os
import datetime

In [6]:
# As colunas devem ser exatamente iguais as colunas que estão nas planilhas
colunas =['Segmento', 'Pais', 'Produto', 'Qtde de Unidades Vendidas', 'Preço Unitário',	'Valor Total',	
          'Desconto', 'Valor Total c/ Desconto', 'Custo Total','Lucro', 'Data', 'Mês', 'Ano']

consolidado = pd.DataFrame(columns=colunas)
consolidado

Empty DataFrame
Columns: [Segmento, Pais, Produto, Qtde de Unidades Vendidas, Preço Unitário, Valor Total, Desconto, Valor Total c/ Desconto, Custo Total, Lucro, Data, Mês, Ano]
Index: []

In [ ]:
caminho = os.getcwd()

c:\Taita Geral\1. CURSOS\Cursos EMPOWERDATA DAXUS\Python\Pequenos_Projetos\Projeto01_Planilhas_Excel

In [8]:
# diretorio = "C:\\Taita Geral\\1. CURSOS\\Cursos EMPOWERDATA DAXUS\\Python\\Projetos\\Projeto01_Planilhas_Excel\\planilhas"
diretorio = caminho + ("\\planilhas")
arquivos = os.listdir(diretorio)

In [9]:
for arq_excel in arquivos:

    if arq_excel.endswith('.xlsx'):
        dados_arquivo = arq_excel.split('-')
        segmento = dados_arquivo[0]
        pais = dados_arquivo[1].replace('.xlsx','')

        try:
            df = pd.read_excel(f'planilhas\\{arq_excel}')
            df.insert(0,'Segmento',segmento)
            df.insert(1,'Pais',pais)
            consolidado = pd.concat([consolidado,df])
        except:
            with open('log_erros.txt','a') as arq_log:
                arq_log.write(f'Erro ao tentar consolidar o arquivo: "{arq_excel}".\n')
    else:
        with open('log_erros.txt','a') as arq_log:
                arq_log.write(f'O arquivo "{arq_excel}" não é um arquivo Excel válido!\n')

C:\Users\tayta\AppData\Local\Temp\ipykernel_3684\1790128441.py:12: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  consolidado = pd.concat([consolidado,df])

In [ ]:
# outra forma de "pegar" apenas o nome do pais, sem o .xlsx (no lugar do replace)
# pais = dados_arquivo[1].split('.')
# pais = pais[0]

In [10]:
consolidado.head()

,Segmento,Pais,Produto,Qtde de Unidades Vendidas,Preço Unitário,Valor Total,Desconto,Valor Total c/ Desconto,Custo Total,Lucro,Data,Mês,Ano
0,Governo,Alemanha,Produto 1,1321,20,26420,0.0,26420.0,14531.0,11889.0,2019-01-01,Janeiro,2019
1,Governo,Alemanha,Produto 1,1513,350,529550,0.0,529550.0,432718.0,96832.0,2019-12-01,Dezembro,2019
2,Governo,Alemanha,Produto 2,2146,7,15022,0.0,15022.0,10730.0,4292.0,2019-09-01,Setembro,2019
3,Governo,Alemanha,Produto 3,1006,350,352100,0.0,352100.0,261560.0,90540.0,2019-06-01,Junho,2019
4,Governo,Alemanha,Produto 3,1513,350,529550,0.0,529550.0,393380.0,136170.0,2019-12-01,Dezembro,2019

In [11]:
consolidado.info()

<class 'pandas.core.frame.DataFrame'>
Index: 700 entries, 0 to 19
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Segmento                   700 non-null    object
 1   Pais                       700 non-null    object
 2   Produto                    700 non-null    object
 3   Qtde de Unidades Vendidas  700 non-null    object
 4   Preço Unitário             700 non-null    object
 5   Valor Total                700 non-null    object
 6   Desconto                   700 non-null    float64
 7   Valor Total c/ Desconto    700 non-null    float64
 8   Custo Total                700 non-null    float64
 9   Lucro                      700 non-null    float64
 10  Data                       700 non-null    datetime64[ns]
 11  Mês                        700 non-null    object
 12  Ano                        700 non-null    object
dtypes: datetime64[ns](1), float64(4), object(8)
memory usage: 76.6+ KB

In [12]:
consolidado.shape

(700, 13)

In [13]:
data_now = datetime.datetime.now()

consolidado.to_excel(f"Report-Consolidado-{data_now.strftime('%d-%m-%Y')}.xlsx",
                     index=False,
                     sheet_name='Report Consolidado')